# This file was automatically generated on Fri 07 Jun 2019 12:12:08 BST from
# source: /dls_sw/prod/R3.14.12.7/support/ADPandABlocks/4-4/etc/makeIocs/example.xml
# 
# *** Please do not edit this file: edit the source file instead. ***
# 
cd "$(INSTALL)"

epicsEnvSet "EPICS_TS_MIN_WEST", '0'


# Loading libraries
# -----------------

# Device initialisation
# ---------------------

cd "$(INSTALL)"

dbLoadDatabase "dbd/pandaApp.dbd"
pandaApp_registerRecordDeviceDriver(pdbbase)

drvAsynIPPortConfigure("PANDA.DRV_CTRL", "172.23.252.202:8888", 100, 0, 0)

drvAsynIPPortConfigure("PANDA.DRV_DATA", "172.23.252.202:8889", 100, 0, 0)

# Create driver
ADPandABlocksConfig("PANDA.DRV", "172.23.252.202", 100000, 1000, 0, 0)

NDAttrPlotConfig("PANDA.PLOT", 198, 50000, 9, "PANDA.DRV", 0, 10000, 0)

# NDFileHDF5Configure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory)
NDFileHDF5Configure("PANDA.HDF", 100, 0, "PANDA.DRV", 0, 0, 0)

# Final ioc initialisation
# ------------------------
cd "$(INSTALL)"
dbLoadRecords 'db/pandaApp.db'
iocInit
