TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

USR_INCLUDES += $(XML2_INCLUDE)

INC += ADPandABlocks.h

LIBRARY_IOC = ADPandABlocks
LIB_SRCS += ADPandABlocks.cpp

DBD += ADPandABlocksSupport.dbd

include $(ADCORE)/ADApp/commonLibraryMakefile
include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

